name: dotnet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup Pkl
      run: |
        mkdir tools
        curl -L -o pkl https://github.com/apple/pkl/releases/download/0.25.2/pkl-linux-amd64
        mv pkl tools/
        echo "$GITHUB_WORKSPACE/tools" >> $GITHUB_PATH
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
